# EDA

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("laptop_price.csv", encoding='latin-1')
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [3]:
data.shape

(1303, 12)

In [4]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [6]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [7]:
data['Ram'] = data['Ram'].str.replace('GB',"").astype('int32')

In [8]:
data['Weight'] = data['Weight'].str.replace('kg','').astype('float32')

In [9]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [10]:
data.corr()['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [11]:
data['Company'].value_counts(0)

Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: Company, dtype: int64

In [12]:
def add_to_other(inp):
    if inp == 'Samsung' or inp == 'Razer' or inp == 'Mediacom' or inp == 'Microsoft' or inp == 'Xiaomi' or inp == 'Vero' or inp == 'Chuwi' or inp == 'Google' or inp == 'Fujitsu' or inp == 'LG' or inp == 'Huawei' :
        return 'Other'
    else:
        return inp

In [13]:
data['Company'] = data['Company'].apply(add_to_other)
data['Company'].value_counts()

Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: Company, dtype: int64

In [14]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [15]:
data['ScreenResolution'].unique()

array(['IPS Panel Retina Display 2560x1600', '1440x900',
       'Full HD 1920x1080', 'IPS Panel Retina Display 2880x1800',
       '1366x768', 'IPS Panel Full HD 1920x1080',
       'IPS Panel Retina Display 2304x1440',
       'IPS Panel Full HD / Touchscreen 1920x1080',
       'Full HD / Touchscreen 1920x1080',
       'Touchscreen / Quad HD+ 3200x1800',
       'IPS Panel Touchscreen 1920x1200', 'Touchscreen 2256x1504',
       'Quad HD+ / Touchscreen 3200x1800', 'IPS Panel 1366x768',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'IPS Panel Full HD 2160x1440',
       '4K Ultra HD / Touchscreen 3840x2160', 'Touchscreen 2560x1440',
       '1600x900', 'IPS Panel 4K Ultra HD 3840x2160',
       '4K Ultra HD 3840x2160', 'Touchscreen 1366x768',
       'IPS Panel Full HD 1366x768', 'IPS Panel 2560x1440',
       'IPS Panel Full HD 2560x1440',
       'IPS Panel Retina Display 2736x1824', 'Touchscreen 2400x1600',
       '2560x1440', 'IPS Panel Quad HD+ 2560x1440',
       'IPS Panel Quad HD+ 3200x1800',
       'IPS Panel Quad HD+ / Touchscreen 3200x1800',
       'IPS Panel Touchscreen 1366x768', '1920x1080',
       'IPS Panel Full HD 1920x1200',
       'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2560x1440',
       'Touchscreen / Full HD 1920x1080', 'Quad HD+ 3200x1800',
       'Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2400x1600'], dtype=object)

In [16]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)

In [17]:
data['IPS'] = data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [18]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [19]:
data['Cpu'] = data['Cpu'].apply(lambda x:' '.join(x.split()[0:3]))

In [20]:
data["Cpu"].value_counts()

Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
Intel Celeron Quad            8
AMD A6-Series 9220            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD A10-Series 9620P          2
Intel Atom X5-Z8350           2
AMD E-Series E2-9000e         2
Intel Xeon E3-1535M           2
Intel Xeon E3-1505M           2
AMD E-Series 7110             2
AMD A10-Series 9600P          2
AMD A6-Series A6-9220         2
AMD A10-Series A10-9620P      2
AMD Ryzen 1600                1
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
AMD E-Series 9000e            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
AMD E-Series 6110             1
Name: Cpu, dtype: int64

In [21]:
def set_processor(name):
    if name == 'Intel Core i7' or name == 'Intel Core i5' or name == 'Intel Core i3':
        return name
    else:
        if name.split()[0] == 'AMD':
            return 'AMD'
        else:
            return 'Other'

In [22]:
data['Cpu'] = data['Cpu'].apply(set_processor)

In [23]:
data['Cpu'].value_counts()

Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: Cpu, dtype: int64

In [24]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [25]:
data['Gpu'] = data['Gpu'].apply(lambda x:' '.join(x.split()[0:1]))
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8,Intel,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8,Intel,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5,8,Intel,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7,16,AMD,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8,Intel,macOS,1.37,1803.60,0,1

In [26]:
data = data[data['Gpu']!='ARM']
data["Gpu"].value_counts()

Intel     722
Nvidia    400
AMD       180
Name: Gpu, dtype: int64

In [27]:
data["OpSys"].value_counts()

Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: OpSys, dtype: int64

In [28]:
def add_os(inp):
    if inp == 'Windows 10' or inp == 'Windows 7' or  inp == 'Windows 10 S':
        return 'Windows'
    elif inp == 'Linux' or inp == 'No OS':
        return inp
    elif inp == 'macOS' or inp == 'Mac OS X':
        return 'Mac'
    else:
        return 'Other'

In [29]:
data["OpSys"] = data["OpSys"].apply(add_os)
data["OpSys"].value_counts()

Windows    1125
No OS        66
Linux        62
Other        28
Mac          21
Name: OpSys, dtype: int64

In [30]:
data = data.drop(columns=['laptop_ID','Inches','Product','ScreenResolution'])

In [31]:
data.head()

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,Apple,Ultrabook,Intel Core i5,8,Intel,Mac,1.37,1339.69,0,1
1,Apple,Ultrabook,Intel Core i5,8,Intel,Mac,1.34,898.94,0,0
2,HP,Notebook,Intel Core i5,8,Intel,No OS,1.86,575.00,0,0
3,Apple,Ultrabook,Intel Core i7,16,AMD,Mac,1.83,2537.45,0,1
4,Apple,Ultrabook,Intel Core i5,8,Intel,Mac,1.37,1803.60,0,1

In [32]:
data = pd.get_dummies(data)
data.head()

,Ram,Weight,Price_euros,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,Cpu_Intel Core i7,Cpu_Other,Gpu_AMD,Gpu_Intel,Gpu_Nvidia,OpSys_Linux,OpSys_Mac,OpSys_No OS,OpSys_Other,OpSys_Windows
0,8,1.37,1339.69,0,1,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1,8,1.34,898.94,0,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
2,8,1.86,575.00,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
3,16,1.83,2537.45,0,1,0,1,0,0,0,...,1,0,1,0,0,0,1,0,0,0
4,8,1.37,1803.60,0,1,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1302 entries, 0 to 1302
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Ram                          1302 non-null   int32
 1   Weight                       1302 non-null   float32
 2   Price_euros                  1302 non-null   float64
 3   Touchscreen                  1302 non-null   int64
 4   IPS                          1302 non-null   int64
 5   Company_Acer                 1302 non-null   uint8
 6   Company_Apple                1302 non-null   uint8
 7   Company_Asus                 1302 non-null   uint8
 8   Company_Dell                 1302 non-null   uint8
 9   Company_HP                   1302 non-null   uint8
 10  Company_Lenovo               1302 non-null   uint8
 11  Company_MSI                  1302 non-null   uint8
 12  Company_Other                1302 non-null   uint8
 13  Company_Toshiba              1302 non-null   uint8
 14  TypeName_2 in 1 Convertible  1302 non-null   uint8
 15  TypeName_Gaming              1302 non-null   uint8
 16  TypeName_Netbook             1302 non-null   uint8
 17  TypeName_Notebook            1302 non-null   uint8
 18  TypeName_Ultrabook           1302 non-null   uint8
 19  TypeName_Workstation         1302 non-null   uint8
 20  Cpu_AMD                      1302 non-null   uint8
 21  Cpu_Intel Core i3            1302 non-null   uint8
 22  Cpu_Intel Core i5            1302 non-null   uint8
 23  Cpu_Intel Core i7            1302 non-null   uint8
 24  Cpu_Other                    1302 non-null   uint8
 25  Gpu_AMD                      1302 non-null   uint8
 26  Gpu_Intel                    1302 non-null   uint8
 27  Gpu_Nvidia                   1302 non-null   uint8
 28  OpSys_Linux                  1302 non-null   uint8
 29  OpSys_Mac                    1302 non-null   uint8
 30  OpSys_No OS                  1302 non-null   uint8
 31  OpSys_Other                  1302 non-null   uint8
 32  OpSys_Windows                1302 non-null   uint8
dtypes: float32(1), float64(1), int32(1), int64(2), uint8(28)
memory usage: 86.5 KB

# Model Building

In [34]:
X = data.drop(columns=['Price_euros'])
y = data['Price_euros']

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [36]:
X_train.shape, X_test.shape

((911, 32), (391, 32))

# Model Training

In [37]:
def model_acc(model):
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(str(model)+ ' --> ' +str(acc))

In [38]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

LinearRegression() --> 0.6634998069817515
Lasso() --> 0.6698723926742742
DecisionTreeRegressor() --> 0.6228351264806264
RandomForestRegressor() --> 0.7612244482867025

# Hyperparameter Tunning

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[20, 40, 60, 80, 100], 'criterion':['squared_error','absolute_error','poisson']}
grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)
grid_fit = grid_obj.fit(X_train, y_train)
best_model = grid_fit.best_estimator_
best_model.score(X_test, y_test)

# Save Model

In [ ]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model,file)

In [ ]:
pred_value = best_model.predict([8, 1.3, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0])
pred_value